-- --------------------------------------------------------
-- Hôte:                         localhost
-- Version du serveur:           5.6.21 - MySQL Community Server (GPL)
-- Serveur OS:                   Win32
-- HeidiSQL Version:             9.1.0.4867
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Export de la structure de table projet. categories
CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '0',
  `parent_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

-- Export de données de la table projet.categories: ~10 rows (environ)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
REPLACE INTO `categories` (`id`, `name`, `parent_id`) VALUES
	(1, 'Marvel', 0),
	(2, 'DC', 0),
	(3, 'Captain America', 1),
	(4, 'Iron Man', 1),
	(5, 'Hulk', 1),
	(6, 'Thor', 1),
	(7, 'Batman', 2),
	(8, 'Superman', 2),
	(9, 'Flash', 2),
	(10, 'Green Arrow', 2);
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;


-- Export de la structure de table projet. items
CREATE TABLE IF NOT EXISTS `items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` longtext NOT NULL,
  `short_description` varchar(100) NOT NULL,
  `pages` int(5) NOT NULL,
  `language` varchar(10) NOT NULL,
  `editor` varchar(50) NOT NULL,
  `price` float NOT NULL,
  `img` varchar(255) NOT NULL,
  `category_id` int(11) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `catégories` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8;

-- Export de données de la table projet.items: ~32 rows (environ)
/*!40000 ALTER TABLE `items` DISABLE KEYS */;
REPLACE INTO `items` (`id`, `name`, `description`, `short_description`, `pages`, `language`, `editor`, `price`, `img`, `category_id`, `created`) VALUES
	(1, 'Captain America #1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Rencontrez Captain America', 52, 'en_US', 'Martin Goodman', 18.99, 'Marvel/captamer/1.jpg', 3, '2014-12-28 13:51:15'),
	(2, 'Captain America #2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'L\'homme sans age qui ne vieilli pas', 52, 'en_US', 'Martin Goodman', 18.97, 'Marvel/captamer/2.jpg', 3, '2014-12-28 13:51:16'),
	(3, 'Captain America #3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le retour de Crâne Rouge', 52, 'en_US', 'Martin Goodman', 19, 'Marvel/captamer/3.jpg', 3, '2014-12-28 13:51:17'),
	(4, 'Captain America #4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'L\'armée morte-vivante', 52, 'en_US', 'Martin Goodman', 16.25, 'Marvel/captamer/4.jpg', 3, '2014-12-28 13:51:18'),
	(5, 'Iron Man #1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Encore Seul', 53, 'en_US', 'Stan Lee', 17.59, 'Marvel/ironman/1.jpg', 4, '2014-12-28 13:51:19'),
	(6, 'Iron Man #2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le jour du démolisseur', 53, 'en_US', 'Stan Lee', 18.65, 'Marvel/ironman/2.jpg', 4, '2014-12-28 13:51:20'),
	(7, 'Iron Man #3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Mon ami, mon ennemi, le monstre !', 53, 'en_US', 'Stan Lee', 17.89, 'Marvel/ironman/3.jpg', 4, '2014-12-28 13:51:21'),
	(8, 'Iron Man #4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'La licorne n\'est pas conquise!', 53, 'en_US', 'Stan Lee', 19.54, 'Marvel/ironman/4.jpg', 4, '2014-12-28 13:51:22'),
	(9, 'Thor #126', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Celui que les dieux veulent détruire !', 89, 'fr_FR', 'Stan Lee', 17.59, 'Marvel/thor/126.jpg', 6, '2014-12-28 13:51:23'),
	(10, 'Thor #127', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le marteau et l\'Holocasut!', 89, 'fr_FR', 'Stan Lee', 17.99, 'Marvel/thor/127.jpg', 6, '2014-12-28 13:51:24'),
	(11, 'Thor #128', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le Pouvoir de Pluton', 89, 'fr_FR', 'Stan Lee', 19.99, 'Marvel/thor/128.jpg', 6, '2014-12-28 13:51:25'),
	(12, 'Thor #129', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le Verdict de Zeus', 89, 'fr_FR', 'Stan Lee', 19.99, 'Marvel/thor/129.jpg', 6, '2014-12-28 13:51:26'),
	(13, 'Hulk #1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'La tempête montante', 56, 'fr_FR', 'Bob Harras', 16.25, 'Marvel/hulk/1.jpg', 5, '2014-12-28 13:51:27'),
	(14, 'Hulk #2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Holocaust dans la Capitale', 56, 'fr_FR', 'Bob Harras', 16.25, 'Marvel/hulk/2.jpg', 5, '2014-12-28 13:51:28'),
	(15, 'Hulk #3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Coeur sombre, Coeur flamboyant', 56, 'fr_FR', 'Bob Harras', 16.25, 'Marvel/hulk/3.jpg', 5, '2014-12-28 13:51:29'),
	(16, 'Hulk #4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Turbulence', 56, 'fr_FR', 'Bob Harras', 16.25, 'Marvel/hulk/4.jpg', 5, '2014-12-28 13:51:30'),
	(17, 'Batman #0', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le commencement de Demain !', 78, 'fr_FR', 'Jenette Kahn', 15.75, 'DC/batman/0.jpg', 7, '2014-12-28 13:51:31'),
	(18, 'Batman #1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le problème du pringtemps', 78, 'fr_FR', 'Jenette Kahn', 15.75, 'DC/batman/1.jpg', 7, '2014-12-28 13:51:32'),
	(19, 'Batman #2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le problème de l\'été', 78, 'fr_FR', 'Jenette Kahn', 15.75, 'DC/batman/2.jpg', 7, '2014-12-28 13:51:33'),
	(20, 'Batman #3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le problème de l\'automne', 78, 'fr_FR', 'Jenette Kahn', 15.75, 'DC/batman/3.jpg', 7, '2014-12-28 13:51:34'),
	(21, 'Superman #1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'L\'histoire complète des exploits du seul et unique Superman', 64, 'fr_FR', 'Vincent Sullivan', 17.75, 'DC/superman/1.jpg', 8, '2014-12-28 13:51:35'),
	(22, 'Superman #2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'L\'histoire complète des exploits de Superman', 64, 'fr_FR', 'Vincent Sullivan', 17.75, 'DC/superman/2.jpg', 8, '2014-12-28 13:51:36'),
	(23, 'Superman #3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le problème de l\'Hiver', 64, 'fr_FR', 'Vincent Sullivan', 17.85, 'DC/superman/3.jpg', 8, '2014-12-28 13:51:37'),
	(24, 'Superman #4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le problème du pringtemps', 64, 'fr_FR', 'Vincent Sullivan', 18.75, 'DC/superman/4.jpg', 8, '2014-12-28 13:51:38'),
	(25, 'Green Arrow #1', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Tout mes sales souvenirs', 65, 'fr_FR', 'Dick Giordano', 15.5, 'DC/greenarrow/1.jpg', 10, '2014-12-28 13:51:39'),
	(26, 'Green Arrow #2', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le cas du Vertigo', 65, 'fr_FR', 'Dick Giordano', 15.5, 'DC/greenarrow/2.jpg', 10, '2014-12-28 13:51:40'),
	(27, 'Green Arrow #3', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'L\'hewagone de la mort', 65, 'fr_FR', 'Dick Giordano', 15.5, 'DC/greenarrow/3.jpg', 10, '2014-12-28 13:51:41'),
	(28, 'Green Arrow #4', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Épreuve de force sur la mer', 65, 'fr_FR', 'Dick Giordano', 15.5, 'DC/greenarrow/4.jpg', 10, '2014-12-28 13:51:42'),
	(29, 'Flash #105', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Conquérant de 8 millions de la Colombie-Britannique', 65, 'fr_FR', 'Carmine Infantino', 17.65, 'DC/flash/105.jpg', 9, '2014-12-28 13:51:43'),
	(30, 'Flash #106', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'La Menace du Super-Gorille', 65, 'fr_FR', 'Carmine Infantino', 17.85, 'DC/flash/106.jpg', 9, '2014-12-28 13:51:44'),
	(31, 'Flash #107', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'Le Retour de Super-Gorille', 65, 'fr_FR', 'Carmine Infantino', 18.05, 'DC/flash/107.jpg', 9, '2014-12-28 13:51:45'),
	(32, 'Flash #108', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad aut dolorem dolores ducimus eligendi eveniet exercitationem fugit id nesciunt nobis nulla odio, odit, pariatur perspiciatis quam quidem recusandae reprehenderit sed tempora totam ullam veritatis voluptate? Alias amet distinctio dolore, eius expedita harum ipsam magnam magni minima nesciunt perspiciatis, placeat quidem, voluptatem! Delectus, incidunt possimus. Aliquid assumenda aut dolorem, ea ex exercitationem facilis impedit in incidunt iusto laborum laudantium minima molestiae nemo nesciunt nihil obcaecati odio officia optio perspiciatis quaerat quia quis suscipit. Aspernatur incidunt mollitia temporibus? Consectetur culpa delectus doloremque eligendi et ex explicabo fuga impedit ipsa iusto laboriosam magni molestiae necessitatibus nihil nostrum obcaecati perspiciatis quidem repellat sapiente tempore, totam unde veniam vitae! Atque aut illo ipsam iure modi perspiciatis placeat quis voluptatum? A architecto consectetur consequatur, culpa facilis id iste nostrum placeat quae reiciendis suscipit tempore tenetur voluptatum. Est minus quos veniam! Ab commodi dolorem eveniet nostrum officiis perspiciatis porro quidem rerum. Ab accusamus alias assumenda aut corporis dolor ducimus earum eius enim eos explicabo facere facilis iste labore laboriosam magni maxime minima modi mollitia nam nihil nisi nobis nostrum pariatur perferendis perspiciatis quasi quia reiciendis rem, sed, temporibus unde velit voluptas. Ab amet at cumque delectus deleniti, dolore ex expedita ipsam libero minus nobis placeat quidem recusandae unde vitae voluptate voluptatum! Dignissimos perferendis praesentium quia repellendus similique sint? Accusamus at aut, autem consectetur corporis dignissimos dolorem dolores eaque eius eos eveniet facilis illum inventore iste magnam maxime necessitatibus nulla quibusdam quod quos ratione sint tempora ut.', 'La vitesse du Destin', 65, 'fr_FR', 'Carmine Infantino', 19.56, 'DC/flash/108.jpg', 9, '2014-12-28 13:51:46');
/*!40000 ALTER TABLE `items` ENABLE KEYS */;


-- Export de la structure de table projet. orders
CREATE TABLE IF NOT EXISTS `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `transaction_id` varchar(50) NOT NULL,
  `payer_id` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'Error',
  `amount` float NOT NULL DEFAULT '0',
  `fee` float NOT NULL DEFAULT '0',
  `gained` float NOT NULL DEFAULT '0',
  `errors` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Export de données de la table projet.orders: ~0 rows (environ)
/*!40000 ALTER TABLE `orders` DISABLE KEYS */;
/*!40000 ALTER TABLE `orders` ENABLE KEYS */;


-- Export de la structure de table projet. users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `firstname` varchar(50) NOT NULL,
  `mail` varchar(255) NOT NULL,
  `password` varchar(50) NOT NULL,
  `street` varchar(255) DEFAULT NULL,
  `zip` int(5) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `token` varchar(50) NOT NULL DEFAULT '0',
  `active` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique` (`mail`),
  KEY `password` (`password`),
  KEY `mail` (`mail`),
  KEY `active` (`active`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- Export de données de la table projet.users: ~2 rows (environ)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
